### DISCUSSION TITLE
docker mods based installation does not seem to work

### DISCUSSION THREAD

**Discussion by maciek226** [VueTorrent/VueTorrent#2075] [Q&A] [answered]
Hi! 
I am trying to use the docker [mods based installation](https://github.com/VueTorrent/VueTorrent/wiki/Installation#using-lsio-docker-mod). When I recreate the container I can see that the mod get applied but the folder does not show up. Anyone have any advice on how to make this work? 

Here are my docker logs:
```
[mod-init] Running Docker Modification Logic
[mod-init] Adding vuetorrent/vuetorrent-lsio-mod:latest to container
[mod-init] Downloading vuetorrent/vuetorrent-lsio-mod:latest from ghcr.io
[mod-init] Installing vuetorrent/vuetorrent-lsio-mod:latest
[mod-init] vuetorrent/vuetorrent-lsio-mod:latest applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 5.0.2-r0-ls367
Build-date: 2024-12-01T06:55:34+00:00
───────────────────────────────────────

[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...
******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080
Connection to localhost (::1) 8080 port [tcp/http-alt] succeeded!
[ls.io-init] done.
```

My qbit config folder looks like this (the underscore folders are manual downloads:
```
root@xopalt:/Config/qbit/qBittorrent# ls
BT_backup        GeoDB       lockfile  nova3             qBittorrent-data.conf  vuetorrent_   watched_folders.json
categories.json  ipc-socket  logs      qBittorrent.conf  rss                    vuetorrent__
```

**Comment by Larsluph** [comment]
Mods folder can be found at `/vuetorrent`

**Reply by maciek226** [reply]
There Is no folder like that, the two with an underscore are the ones I added manually

**Reply by Larsluph** [reply]
The `vuetorrent` folder is located at the root of the filesystem

**Reply by maciek226** [reply]
The root of the docker container? 
```
root@xopalt:/Config/qbit# ls
qBittorrent  Trash
```

The root of the file system all together? There is nothing. Download folder? Also, not there.

**Reply by Larsluph** [reply, marked as answer]
What you're looking at is not the root of the container, you're inside the `/Config/qbit` folder.

**Comment by maciek226** [comment]
For context, this is the fragment of my docker compose
```
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest 

    volumes:
      - /Config/qbit:/config
      - /srv/dev-disk-by-uuid-963349e1-e758-4b27-9598-cf865a46a49f/downloads:/downloads
```
