### ISSUE TITLE
[Bug]: Upload speeds and download speeds showing zero seeds also showing 0

### ISSUE THREAD

**Issue by Ghostraven192** [VueTorrent/VueTorrent#1577]
### Bug description

Running latest ghcr.io/hotio/qbittorrent
With Wireguard VPN
Vuetorrent is working and communicating with webgui of qbittorrent
Torrents sucessfully download and seed
however download speed shows zero
Upload speed shows zero
Seeds show zero
Torrent status says seeding
Vuetorrent is installed and mapped inside docker compose

Here is my compose file:

```yml
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - '8080:8080'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - 'WEBUI_PORTS=8080/tcp,8080/udp'
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=10.0.0.0/24
      - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_AUTO_PORT_FORWARD_TO_PORTS=
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - VPN_PIA_USER=XXXXXXXXXXXX
      - VPN_PIA_PASS=XXXXXXXXXXXX
      - VPN_PIA_PREFERRED_REGION
      - VPN_PIA_DIP_TOKEN=no
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
    volumes:
      - '/docker/qbittorrent/config:/config'
      - '/docker/qbittorrent/data:/data'
      - '/docker/qbittorrent/vuetorrent:/vuetorrent'
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    devices:
      - '/dev/net/tun:/dev/net/tun'
```

### Expectations

Speed stats to show up.

### Steps to reproduce

1. ...Install Latest qbittorrent docker from ghcr.io/hotio/qbittorrent
2. ...Grab latest Vuetorrent
3. Map in docker compose

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: Debian 12 with Docker

PWA: No
Running inside a container: Yes
```

### qBittorrent version

4.6.3

### VueTorrent version

2.7.1

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
