### ISSUE TITLE
[Bug]: "Bypass authentication for clients in whitelisted IP subnets" setting does not work anymore

### ISSUE THREAD

**Issue by ClementNerma** [VueTorrent/VueTorrent#2028]
### Bug description

Hi there!

Since two or three versions (I don't know exactly) the `Bypass authentication for clients in whitelisted IP subnets` doesn't seem to work anymore.

Here are my settings:

![image](https://github.com/user-attachments/assets/ee9fb8f7-5eb7-40cd-9a76-715f090267ef)

And the network panel:

![image](https://github.com/user-attachments/assets/17b6323e-a8a1-4f6a-8d00-463312b6431e)

### Expectations

The credentials panel shouldn't appear on the whitelisted IPs

### Relevant debug informations

As indicated above.

### Steps to reproduce

As indicated above.

### How did you install VueTorrent?

Using an official docker image (vuetorrent-lsio-mod, vuetorrent-backend)

### Environment description

```plain text
Device type: Desktop
OS: Linux
Browser (name and version): Firefox Developer Edition 133.0b5 (64-bit)

PWA: No
Running inside a container: Yes (Docker)
```

### qBittorrent version

5.0.1

### VueTorrent version

2.16.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
What is the status code and body of the `version` request in the network panel? This request is the one responsible for showing the login screen.

**Comment by ClementNerma** [comment]
It returns a 403 with body `Forbidden`.

I also get other network errors even after logging in:

![image](https://github.com/user-attachments/assets/6de47caa-3cf4-421b-9085-04c0e2f52e2a)

**Comment by Larsluph** [comment]
Then you didn't configure something properly.

If you're using the backend, make sure you're accessing the backend directly instead of qBittorrent. It will forward all requests as needed.

If you're using the docker mod, the WebUI path in qBittorrent must be `/vuetorrent`.

**Comment by ClementNerma** [comment]
The path in the WebUI is correct. I installed VueTorrent using the recommended docker compose file:

```yaml
services:
  qbit:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ../../data/qBittorrent/:/config
      - /media/mydisk/Torrents/:/downloads
    ports:
      - '8080:8080'
      - '6881:6881'
      - '6881:6881/udp'
```
